# numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.
File automatically generated. See the documentation to update questions/answers/hints programmatically.




In [2]:
#### 1. Import the numpy package under the name `np` (★☆☆)
#`hint: import … as`
import numpy as np

In [20]:
#### 2. Create a null vector of size 10 (★☆☆)
#`hint: np.zeros`
a = np.zeros((10))
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
#`hint: array[4]`
a[4] = 1
print(a)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [31]:
#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
#`hint: arange`

b = np.arange(10,50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [34]:
#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
#`hint: reshape`

c = np.arange(0, 9).reshape((3, 3))
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [40]:
#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
#`hint: np.nonzero`

d = np.array([1,2,0,0,4,0])
np.nonzero(d)


(array([0, 1, 4]),)

In [43]:
#### 7. Create a 3x3 identity matrix (★☆☆)
#`hint: np.eye

e = np.eye(3, 3)
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [47]:
#### 8. Create a 3x3x3 array with random values (★☆☆)
#`hint: np.random.random`

f = np.random.random([3, 3, 3])
print(f)

[[[0.55532834 0.41501755 0.94763338]
  [0.67033922 0.79877287 0.04569334]
  [0.21058181 0.50800797 0.83277998]]

 [[0.03899891 0.03539502 0.39172542]
  [0.46091547 0.01473856 0.49805008]
  [0.86068201 0.48824381 0.08827804]]

 [[0.00130577 0.50447877 0.52451884]
  [0.46103318 0.30492517 0.77229115]
  [0.04940909 0.96233815 0.88465087]]]


In [56]:
#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
#`hint: min, max

g = np.random.random([10, 10])

max_element = np.max(g)
min_element = np.min(g)


print(max_element, min_element)

0.9973888335898248 4.4848260572827314e-05


In [58]:
#or without assigment
g = np.random.random([10, 10])

print(np.max(g))
print(np.min(g))


0.9999121203809221
0.009260726388661822


In [62]:
#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
#`hint: mean`

h = np.random.random(30)

print(np.mean(h))

0.6332327262752118


In [65]:
#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
#`hint: np.diag`
    
i = np.eye(5,5)

i[4,0] = 1
i[4,1] = 2
i[4,2] = 3
i[4,3] = 4

print(i)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [1. 2. 3. 4. 1.]]


In [82]:
#### 12. Normalize a 5x5 random matrix (★☆☆)
#`hint: (x -mean)/std`

j = np.random.random([5,5])
normalize_j = (j - np.mean(j)/np.std(j))

print(normalize_j)

[[-1.58876459 -1.08284563 -0.72543241 -1.57864638 -1.04565336]
 [-0.9428561  -0.74558183 -1.25703206 -1.56224335 -0.67831088]
 [-1.41018305 -1.1602061  -1.08286313 -1.51764776 -0.70575765]
 [-1.080261   -0.80922604 -1.10241159 -0.8096242  -1.38077442]
 [-1.04576646 -1.58253964 -0.76689524 -0.83780646 -1.47065108]]


In [134]:
#### 13. How to find common values between two arrays? (★☆☆)
#`hint: np.intersect1d`

k = np.arange(4)
l = np.arange(10)

common_values = np.intersect1d([k], [l])

print(common_values)



[0 1 2 3]


In [135]:
#### 14. Create a random vector of size 10 and sort it (★★☆)
#`hint: sort`
    
m = np.random.random(10)

print(np.sort(m))

[0.00244062 0.06102892 0.10036754 0.31101437 0.40912993 0.41155923
 0.58810023 0.71099264 0.7426656  0.94875304]


In [15]:
#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
#`hint: argmax`
    
n = np.random.random(10)
position = np.where(n == max(n))
n[position]=0

#max_value = np.max(n)




print(n)




[0.16168233 0.97952292 0.2853989  0.49562692 0.72092716 0.47245792
 0.21242994 0.26802774 0.03595222 0.        ]


In [ ]:
#numpy.argmax(a, axis=None, out=None, *, keepdims=<no value>)[source]

In [117]:
#### 16. Subtract the mean of each row of a matrix (★★☆)
#`hint: mean(axis=,keepdims=)`

x = np.random.random([2, 2])
print(x)




[[0.38339086 0.37561506]
 [0.20117335 0.86447359]]


In [118]:
print(np.mean(x, axis= 0,keepdims= True))

print(np.mean(x, axis= 1,keepdims= True))

[[0.2922821  0.62004433]]
[[0.37950296]
 [0.53282347]]


In [122]:
#### 17. How to get the n largest values of an array (★★★)
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
#hint: np.argsort | np.argpartition`

sorted_index_array = np.argsort(Z)
sorted_array = Z[sorted_index_array]


rslt = sorted_array[-n : ]

print("{} largest value:".format(n),
      rslt[0])


5 largest value: 9995


In [19]:
#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
#`hint: np.where`
#array = np.random.randint(10, size=(2, 3))
#np.where(a < 5, a, 10*a)

m = np.random.randint(10, size=(5, 3))

m = np.where((m > 4), m**2, m)

print(m) 
#arr2 = arr[np.where((arr >5) & (arr 5) | (arr % 5 == 0))]



[[ 2 36 81]
 [ 1  0 25]
 [49  3 64]
 [64 64 36]
 [81  3 25]]
